# Generated by Django 5.2.3 on 2025-07-03 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='sentiment',
            field=models.CharField(default='neutral', max_length=10),
        ),
    ]
