# Generated by Django 5.2.3 on 2025-07-03 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0002_feedback_sentiment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='sentiment',
        ),
    ]
