# Generated by Django 5.2.3 on 2025-07-03 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0003_remove_feedback_sentiment'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='sentiment',
            field=models.CharField(default='neutral', max_length=10),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='category',
            field=models.CharField(choices=[('feature', 'Feature Request'), ('bug', 'Bug Report'), ('general', 'General')], max_length=20),
        ),
    ]
