# Generated by Django 5.2.3 on 2025-07-03 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0004_feedback_sentiment_alter_feedback_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='type',
            field=models.CharField(choices=[('product', 'Product'), ('service', 'Service')], default='product', max_length=10),
        ),
    ]
