# Generated by Django 5.2.3 on 2025-07-05 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0005_feedback_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='sentiment',
            field=models.CharField(blank=True, default='neutral', max_length=10, null=True),
        ),
    ]
